package corepack

const outputExactRefSchemaV1 = `{"additionalProperties":false,"properties":{"digest":{"minLength":1,"type":"string"},"id":{"minLength":1,"type":"string"},"revision":{"minimum":1,"type":"integer"}},"required":["id","revision","digest"],"type":"object"}`
const outputFileRefSchemaV1 = `{"additionalProperties":false,"properties":{"digest":{"minLength":1,"type":"string"},"path":{"maxLength":4096,"minLength":1,"type":"string"},"revision":{"minimum":1,"type":"integer"}},"required":["path","revision","digest"],"type":"object"}`
const outputWindowPropertiesV1 = `"checked_unix_nano":{"minimum":1,"type":"integer"},"expires_unix_nano":{"minimum":1,"type":"integer"}`
const nullableExactRefSchemaV1 = `{"anyOf":[` + outputExactRefSchemaV1 + `,{"type":"null"}]}`

const workspaceReadOutputSchemaStrictV1 = `{"additionalProperties":false,"oneOf":[{"properties":{"artifact_ref":{"type":"null"},"content":{"maxLength":1048576,"type":"string"}}},{"properties":{"artifact_ref":` + outputExactRefSchemaV1 + `,"content":{"type":"null"}}}],"properties":{"artifact_ref":` + nullableExactRefSchemaV1 + `,"bytes_returned":{"maximum":1048576,"minimum":0,"type":"integer"},"complete":{"type":"boolean"},"content":{"type":["string","null"]},"file":` + outputFileRefSchemaV1 + `,"start_byte":{"minimum":0,"type":"integer"},"total_bytes":{"minimum":0,"type":"integer"},` + outputWindowPropertiesV1 + `},"required":["file","start_byte","bytes_returned","total_bytes","complete","content","artifact_ref","checked_unix_nano","expires_unix_nano"],"type":"object"}`

const workspaceSearchMatchSchemaV1 = `{"additionalProperties":false,"properties":{"end_byte":{"minimum":0,"type":"integer"},"file_digest":{"minLength":1,"type":"string"},"file_revision":{"minimum":1,"type":"integer"},"path":{"maxLength":4096,"minLength":1,"type":"string"},"preview":{"maxLength":8192,"type":"string"},"start_byte":{"minimum":0,"type":"integer"}},"required":["path","file_revision","file_digest","start_byte","end_byte","preview"],"type":"object"}`
const workspaceSearchOutputSchemaStrictV1 = `{"additionalProperties":false,"oneOf":[{"properties":{"artifact_ref":{"type":"null"},"matches":{"items":` + workspaceSearchMatchSchemaV1 + `,"maxItems":200,"type":"array"}}},{"properties":{"artifact_ref":` + outputExactRefSchemaV1 + `,"matches":{"maxItems":0,"type":"array"}}}],"properties":{"artifact_ref":` + nullableExactRefSchemaV1 + `,"complete":{"type":"boolean"},"matches":{"items":` + workspaceSearchMatchSchemaV1 + `,"maxItems":200,"type":"array"},"workspace_digest":{"minLength":1,"type":"string"},"workspace_revision":{"minimum":1,"type":"integer"},` + outputWindowPropertiesV1 + `},"required":["workspace_revision","workspace_digest","matches","complete","artifact_ref","checked_unix_nano","expires_unix_nano"],"type":"object"}`

const workspaceMetadataSchemaV1 = `{"additionalProperties":false,"properties":{"digest":{"minLength":1,"type":"string"},"kind":{"enum":["file","directory","symlink"]},"link_target":{"maxLength":4096,"type":"string"},"mode":{"minimum":0,"type":"integer"},"modified_unix_nano":{"minimum":1,"type":"integer"},"path":{"maxLength":4096,"type":"string"},"revision":{"minimum":1,"type":"integer"},"size_bytes":{"minimum":0,"type":"integer"}},"required":["path","kind","revision","digest","size_bytes","mode","modified_unix_nano"],"type":"object"}`
const workspaceInspectOutputSchemaStrictV1 = `{"additionalProperties":false,"properties":{"complete":{"type":"boolean"},"entries":{"items":` + workspaceMetadataSchemaV1 + `,"maxItems":1000,"type":"array"},"object":` + workspaceMetadataSchemaV1 + `,"range_valid":{"type":"boolean"},` + outputWindowPropertiesV1 + `},"required":["object","range_valid","entries","complete","checked_unix_nano","expires_unix_nano"],"type":"object"}`

const workspacePatchOutputSchemaStrictV1 = `{"additionalProperties":false,"properties":{"base_workspace":` + outputExactRefSchemaV1 + `,"change_set_ref":` + outputExactRefSchemaV1 + `,"files":{"items":` + outputFileRefSchemaV1 + `,"maxItems":64,"minItems":1,"type":"array"},"result_workspace":` + outputExactRefSchemaV1 + `,` + outputWindowPropertiesV1 + `},"required":["change_set_ref","base_workspace","result_workspace","files","checked_unix_nano","expires_unix_nano"],"type":"object"}`

const processExecOutputSchemaStrictV1 = `{"additionalProperties":false,"allOf":[{"oneOf":[{"properties":{"stdout":{"maxLength":1048576,"type":"string"},"stdout_artifact_ref":{"type":"null"}}},{"properties":{"stdout":{"type":"null"},"stdout_artifact_ref":` + outputExactRefSchemaV1 + `}}]},{"oneOf":[{"properties":{"stderr":{"maxLength":1048576,"type":"string"},"stderr_artifact_ref":{"type":"null"}}},{"properties":{"stderr":{"type":"null"},"stderr_artifact_ref":` + outputExactRefSchemaV1 + `}}]}],"properties":{"attempt_ref":` + outputExactRefSchemaV1 + `,"exit_code":{"type":"integer"},"stderr":{"type":["string","null"]},"stderr_artifact_ref":` + nullableExactRefSchemaV1 + `,"stdout":{"type":["string","null"]},"stdout_artifact_ref":` + nullableExactRefSchemaV1 + `,"timed_out":{"type":"boolean"},` + outputWindowPropertiesV1 + `},"required":["attempt_ref","exit_code","stdout","stderr","stdout_artifact_ref","stderr_artifact_ref","timed_out","checked_unix_nano","expires_unix_nano"],"type":"object"}`
